services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\Sitemap\Service\XmlGeneratorInterface:
    class: FreshAdvance\Sitemap\Service\XmlGenerator

  FreshAdvance\Sitemap\Service\Sitemap:
    class: FreshAdvance\Sitemap\Service\Sitemap

  FreshAdvance\Sitemap\Service\Filesystem:
    class: FreshAdvance\Sitemap\Service\Filesystem

  FreshAdvance\Sitemap\Service\ModuleSettings:
    class: FreshAdvance\Sitemap\Service\ModuleSettings

  FreshAdvance\Sitemap\Service\ChangeFilterInterface:
    class: FreshAdvance\Sitemap\Service\ChangeFilter
    args:
      $filters: !tagged 'sitemap.change_filter'
