services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\Sitemap\Service\XmlGeneratorInterface:
    class: FreshAdvance\Sitemap\Service\XmlGenerator

  FreshAdvance\Sitemap\Service\Sitemap:
    class: FreshAdvance\Sitemap\Service\Sitemap
