imports:
  - { resource: src/ChangeFilter/services.yaml }
  - { resource: src/Command/services.yaml }
  - { resource: src/Repository/services.yaml }
  - { resource: src/Sitemap/services.yaml }
  - { resource: src/Service/services.yaml }
  - { resource: src/Settings/services.yaml }
  - { resource: src/Url/services.yaml }

services:
    _defaults:
        public: false
        autowire: true

    FreshAdvance\Sitemap\Core\Registry:
        class: OxidEsales\Eshop\Core\Registry
        public: true
