parameters:
  sitemap.object_type.product: 'product'

services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\Sitemap\ChangeFilter\Product\ProductChangeFilter:
    arguments:
      $objectType: '%sitemap.object_type.product%'
      $modelItemRepository: '@FreshAdvance\Sitemap\ChangeFilter\Product\ProductChangeFilterItemRepository'
    tags:
      - 'sitemap.change_filter'

  FreshAdvance\Sitemap\ChangeFilter\Product\ProductChangeFilterItemRepository:
    class: FreshAdvance\Sitemap\ChangeFilter\Shared\Repository\ModelItemRepository
    arguments:
      $model: '\OxidEsales\Eshop\Application\Model\Article'

  FreshAdvance\Sitemap\ChangeFilter\Product\ProductUrlType:
    class: FreshAdvance\Sitemap\Url\DataType\UrlType
    arguments:
      $objectType: '%sitemap.object_type.product%'
      $changeFrequency: 'daily'
      $priority: 0.4
    tags:
      - 'sitemap.page_type_configuration'
