parameters:
  sitemap.object_type.additional: 'additional'

services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\Sitemap\ChangeFilter\Additional\AdditionalChangeFilter:
    arguments:
      $objectType: '%sitemap.object_type.additional%'
    tags:
      - 'sitemap.change_filter'

  FreshAdvance\Sitemap\ChangeFilter\Additional\AdditionalUrlType:
    class: FreshAdvance\Sitemap\Url\DataType\UrlType
    arguments:
      $objectType: '%sitemap.object_type.additional%'
      $changeFrequency: 'daily'
      $priority: 0.85
    tags:
      - 'sitemap.page_type_configuration'
