parameters:
  sitemap.object_type.category: 'category'

services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\Sitemap\ChangeFilter\Category\CategoryChangeFilter:
    arguments:
      $objectType: '%sitemap.object_type.category%'
      $modelItemRepository: '@FreshAdvance\Sitemap\ChangeFilter\Category\CategoryChangeFilterItemRepository'
    tags:
      - 'sitemap.change_filter'

  FreshAdvance\Sitemap\ChangeFilter\Category\CategoryChangeFilterItemRepository:
    class: FreshAdvance\Sitemap\ChangeFilter\Shared\Repository\ModelItemRepository
    arguments:
      $model: '\OxidEsales\Eshop\Application\Model\Category'

  FreshAdvance\Sitemap\ChangeFilter\Category\CategoryUrlType:
    class: FreshAdvance\Sitemap\Url\DataType\UrlType
    arguments:
      $objectType: '%sitemap.object_type.category%'
      $changeFrequency: 'daily'
      $priority: 0.7
    tags:
      - 'sitemap.page_type_configuration'
