imports:
  - { resource: Service/services.yaml }

services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\Sitemap\Integration\Command\UpdateTypeCommand:
    tags:
      - { name: 'console.command', command: 'fa:sitemap:update' }
