services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\Sitemap\Url\DataTypeFactory\UrlFactoryInterface:
    class: FreshAdvance\Sitemap\Url\DataTypeFactory\UrlFactory

  FreshAdvance\Sitemap\Url\DataTypeFactory\UrlTypeFactoryInterface:
    class: FreshAdvance\Sitemap\Url\DataTypeFactory\UrlTypeFactory
    arguments:
      $configurations: !tagged 'sitemap.page_type_configuration'
      $defaultConfiguration: '@FreshAdvance\Sitemap\Url\DataTypeFactory\DefaultUrlType'

  FreshAdvance\Sitemap\Url\DataTypeFactory\DefaultUrlType:
    class: FreshAdvance\Sitemap\Url\DataType\UrlType
    arguments:
      $objectType: 'default'
      $changeFrequency: 'daily'
      $priority: 0.5
